# å¯ç”¨æœç´¢
enableSearch = true

# ç¤¾äº¤åª’ä½“
twitter = "@janedoe"
largeTwitterCard = false # å¦‚æœè¦æ˜¾ç¤ºå¤§çš„ Twitter å¡ç‰‡å›¾åƒï¼Œè¯·è®¾ç½®ä¸º trueã€‚é»˜è®¤ä¸ºå°çš„ Twitter å¡ç‰‡å›¾åƒ
introDescription = "æŠ€æœ¯ä¸“å®¶ï¼Œæ°¸ä¹…å­¦ç”Ÿï¼Œæ•™å¸ˆï¼Œä¸æ–­å¢é‡æ”¹è¿›ã€‚"
# introURL = "about/" # è®¾ç½®â€œé˜…è¯»æ›´å¤šâ€æŒ‰é’®ä¸‹é¢çš„ urlï¼Œæˆ–å°†å…¶è®¾ç½®ä¸º false ä»¥ä¸æ˜¾ç¤ºè¯¥æŒ‰é’®
# description = "A theme based on VMware's Clarity Design System for publishing technical blogs with Hugo." # åœ¨æ­¤å¤„è®¾ç½®æ‚¨ç½‘ç«™çš„å…ƒæ ‡è®°ï¼ˆSEOï¼‰æè¿°ã€‚æˆ–è€…åœ¨ä¸»é¡µå†…å®¹æ–‡ä»¶ï¼ˆä¾‹å¦‚ content/_index.mdï¼‰ä¸­è®¾ç½®æ­¤æè¿°ã€‚ä»¥åè€…è®¾ç½®çš„ä¸ºå‡†ã€‚
# keywords = ["design", "clarity", "hugo theme"] # åœ¨æ­¤å¤„è®¾ç½®æ‚¨ç½‘ç«™çš„å…ƒæ ‡è®°ï¼ˆSEOï¼‰å…³é”®å­—ã€‚æˆ–è€…åœ¨ä¸»é¡µå†…å®¹æ–‡ä»¶ï¼ˆä¾‹å¦‚ content/_index.mdï¼‰ä¸­è®¾ç½®è¿™äº›å…³é”®å­—ã€‚ä»¥åè€…è®¾ç½®çš„ä¸ºå‡†ã€‚

# showShare = false # å–æ¶ˆæ³¨é‡Šä»¥åœ¨æ¯ç¯‡æ–‡ç« ä¸Šä¸æ˜¾ç¤ºå…±äº«æŒ‰é’®ã€‚ä¹Ÿå¯åœ¨æ¯ç¯‡æ–‡ç« çš„å‰ç½®å…ƒæ•°æ®ä¸­è®¾ç½®ã€‚

# Google åˆ†æ ID
ga_analytics = ""

# Google æ ‡ç­¾ç®¡ç†å™¨
google_tag_manager_id = ""

# ç™¾åº¦åˆ†æ ID
# baidu_analytics = "XXXXXXXX"

# é»˜è®¤æƒ…å†µä¸‹é™åˆ¶ä¾§è¾¹æ ä¸Šæ˜¾ç¤ºçš„åˆ†ç±»é“¾æ¥æ•°ã€‚
numberOfTagsShown = 14 # é€‚ç”¨äºæ‰€æœ‰å…¶ä»–é»˜è®¤å’Œè‡ªå®šä¹‰åˆ†ç±»ã€‚ä¾‹å¦‚ï¼Œç±»åˆ«ã€å“ç‰Œç­‰ï¼Œè¯·å‚è§ https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# æ˜¯å¦é»˜è®¤å°†å›¾åƒå’Œå…¶ä»–èµ„æºå­˜å‚¨åœ¨â€œstaticâ€ç›®å½•ä¸­ï¼Œæˆ–ä½¿ç”¨ Hugo é¡µé¢åŒ…ã€‚
# å¦‚æœæ‚¨æƒ³å°†èµ„äº§ä¸å¸–å­æœ¬èº«åˆ†ç»„ï¼ˆä½œä¸ºâ€œå¶å­åŒ…â€ï¼‰ï¼Œè¯·åˆ‡æ¢ä¸ºâ€œtrueâ€ã€‚
# è¿™å¯ä»¥åœ¨é¡µé¢çº§åˆ«ä¸Šè¦†ç›–ï¼›å¦‚æœæ²¡æœ‰è®¾ç½®é¡µé¢å˜é‡ï¼Œåˆ™ä¸‹é¢è®¾ç½®çš„å†…å®¹ä¸ä¼šè¢«æ›´æ”¹ã€‚
usePageBundles = false

# è·¯å¾„å˜é‡
#
# é»˜è®¤æƒ…å†µä¸‹ï¼Œè¿™äº›ç›®å½•éƒ½æ˜¯â€œstaticâ€ç›®å½•çš„å­ç›®å½•ã€‚
#
# åœ¨æŸäº› Apache æœåŠ¡å™¨å®‰è£…ä¸­ï¼Œè¿™äº›ç›®å½•åç§°å¯èƒ½ä¼šå†²çªï¼Œæ‚¨å¯èƒ½å¸Œæœ›æ›´æ”¹å®ƒä»¬ã€‚è¯·å‚è§ï¼š
# https://github.com/chipzoller/hugo-clarity/issues/74
#
# å¦‚æœæ›´æ”¹è¿™äº›ç›®å½•çš„åç§°ï¼Œè¯·åŠ¡å¿…å¤åˆ¶åŸå§‹å†…å®¹ä»¥è·å–åŒ…å«åœ¨ Hugo Clarity ä¸­çš„æ–‡ä»¶ã€‚
#
# å›¾åƒï¼š
imagesDir = "images/" # æ²¡æœ‰å‰å¯¼æ­£æ–œæ 
# å›¾æ ‡ï¼š
iconsDir = "icons/" # æ²¡æœ‰å‰å¯¼æ­£æ–œæ 
# å­—ä½“ï¼š
fontsDir = "fonts/" # æ²¡æœ‰å‰å¯¼æ­£æ–œæ 

# ç¤¾äº¤åª’ä½“å…±äº«å›¾åƒï¼šå½“ç»™å®šé¡µé¢æ²¡æœ‰å…¶ä»–å›¾åƒæ—¶ï¼Œå°†åœ¨ Twitterã€Facebookã€LinkedIn ç­‰ä¸Šä½¿ç”¨ã€‚
fallBackOgImage = "images/thumbnail.png"

# Logo å›¾åƒ
logo = "logos/logo.png"

# åœ¨å¯¼èˆªæ ä¸Šå±…ä¸­ Logo
centerLogo = false # è®¾ç½®ä¸ºâ€œtrueâ€ä»¥å±…ä¸­ï¼Œè®¾ç½®ä¸ºâ€œfalseâ€ä»¥å·¦å¯¹é½ã€‚

# è®¾ç½®æ¯ä¸ªä»£ç å—çš„æœ€å¤§è¡Œæ•°ã€‚ä½†æ˜¯ï¼Œä»£ç å—å°†æ˜¯å¯æ»šåŠ¨å’Œå¯æ‰©å±•çš„ã€‚
codeMaxLines = 7

# é»˜è®¤æƒ…å†µä¸‹ç¦ç”¨æ˜¾ç¤ºè¡Œå·ã€‚å¦‚æœæ‚¨å¸Œæœ›æ‰“å¼€å®ƒä»¬ï¼Œè¯·åˆ‡æ¢åˆ°â€œtrueâ€ã€‚
codeLineNumbers = false

# å¯ç”¨æ•°å­¦ç¬¦å·ã€‚åˆ‡æ¢åˆ°â€œtrueâ€ä»¥åœ¨æ‚¨çš„ç«™ç‚¹ä¸­å¯ç”¨ mathjaxã€‚
enableMathNotation = false

# æ‚¨çš„æ–‡ç« æ‰€åœ¨çš„ç›®å½•
mainSections = ["post"] # è¯¦ç»†ä¿¡æ¯è¯·å‚è§ https://gohugo.io/functions/where/#mainsections

# åœ¨æ–‡ç« æ­£æ–‡ä¸­æ ‡è®°éå†…è”å›¾åƒ
figurePositionShow = false # å…¨å±€åˆ‡æ¢æ‰“å¼€æˆ–å…³é—­
# æ‚¨å¯ä»¥åœ¨æ–‡ç« çš„å‰ç½®å…ƒæ•°æ®ä¸­ä½¿ç”¨ç›¸åŒçš„å˜é‡ï¼Œä»¥åœ¨æ¯ä¸ªé¡µé¢ä¸Šåˆ‡æ¢æ­¤è¡Œä¸ºæ‰“å¼€æˆ–å…³é—­
figurePositionLabel = "Figure" # å›¾åƒç¼–å·å‰çš„æ–‡æœ¬ï¼Œä¾‹å¦‚ Figure 1.0

# å°†æŠ˜å çš„ç§»åŠ¨å¯¼èˆªè®¾ç½®ä¸ºä»å·¦ä¾§æˆ–å³ä¾§å‡ºç°
mobileNavigation = "left" # å¦‚æœæ‚¨å–œæ¬¢å³ä¾§ï¼Œè¯·æ›´æ”¹ä¸ºâ€œrightâ€

# ä¸€äº›ç½‘ç«™æ‰€æœ‰è€…å¸Œæœ›å†³å®šä»–ä»¬å¸Œæœ›å¦‚ä½•å‘ç”¨æˆ·ä»‹ç»ä»–ä»¬çš„ç½‘ç«™ã€‚è¿™äº›è®¾ç½®ä¸ºæ‚¨ä½œä¸ºç½‘ç«™æ‰€æœ‰è€…å†³å®šç”¨æˆ·å°†å¦‚ä½•é¦–æ¬¡æŸ¥çœ‹æ‚¨çš„ç«™ç‚¹ã€‚

# è¯·æ³¨æ„ï¼Œæ‚¨ä¸èƒ½åŒæ—¶å¼ºåˆ¶æ‰§è¡Œä¸¤ç§æ¨¡å¼ã€‚å³é€šè¿‡å¼ºåˆ¶æ‰§è¡Œä¸€ç§æ¨¡å¼ï¼Œæ‚¨ä¼˜å…ˆè€ƒè™‘å®ƒï¼ˆé€šè¿‡å°†å…¶è®¾ç½®ä¸º trueï¼‰ã€‚enforceDarkMode å°†è¢«æ³¨é‡Šæ‰

# è¯·æ³¨æ„ï¼Œæ¨¡å¼åˆ‡æ¢ UI å°†ä¿æŒä¸å˜ã€‚è¿™æ ·ï¼Œå¦‚æœç”¨æˆ·å–œæ¬¢æš—æ¨¡å¼ï¼Œä»–ä»¬å¯ä»¥éšå¿ƒæ‰€æ¬²ã€‚

enforceLightMode = false

# è‡ªå®šä¹‰é¡µè„šå›¾æ ‡ã€‚è¯·å‚è§é—®é¢˜ https://github.com/chipzoller/hugo-clarity/issues/77
# footerLogo = "icons/copy.svg"

# è‡ªå®šä¹‰ä¾§è¾¹æ å…è´£å£°æ˜æ–‡æœ¬
# sidebardisclaimer = true
# disclaimerText = "æœ¬ç«™ç‚¹ä¸Šè¡¨è¾¾çš„è§‚ç‚¹æ˜¯æˆ‘ä¸ªäººçš„è§‚ç‚¹ï¼Œä¸ä»£è¡¨æˆ‘çš„é›‡ä¸»çš„ä»»ä½•è§‚ç‚¹ã€‚"

# è¯­è¨€èœå•çš„æ–‡æœ¬ã€‚
languageMenuName = "ğŸŒ"

# æ ‡é¢˜åˆ†éš”ç¬¦ï¼Œé»˜è®¤ä¸º |ã€‚
# titleSeparator = "|"

# å…¨å±€å¯ç”¨æˆ–ç¦ç”¨è¯„è®ºã€‚é»˜è®¤ä¸º trueã€‚
# comments = false

# å…¨å±€å¯ç”¨æˆ–ç¦ç”¨ Utterances (https://github.com/utterance/utterances) åŸºäº Github çš„è¯„è®º
# utterances = true  #åœ¨ single.html å¸ƒå±€ä¸­è¿è¡Œ utterances è„šæœ¬ä»¥åŠ è½½ https://utteranc.es è¯„è®º
# utterancesRepo = "GHUsername/Repository.Name" # è®¾ç½®æ­¤å‚æ•°æ—¶å¯ç”¨ Utterances
# utterancesTheme = "github-light" # é»˜è®¤å€¼ï¼šgithub-dark
# utterancesIssueTerm = "pathname" # é»˜è®¤å€¼ï¼špathname

# æœ€è¿‘æ–‡ç« çš„æœ€å¤§æ•°é‡ã€‚ (é»˜è®¤å€¼ï¼š8)
# numberOfRecentPosts = 8

# ç‰¹è‰²æ–‡ç« çš„æœ€å¤§æ•°é‡ã€‚ (é»˜è®¤å€¼ï¼š8)
# numberOfFeaturedPosts = 8

# åœ¨åˆ—è¡¨ä¸­å›ºå®šç‰¹è‰²æ–‡ç« ã€‚
# pinFeatured = true

# å›ºå®šç‰¹è‰²æ–‡ç« çš„æœ€å¤§æ•°é‡ã€‚ (é»˜è®¤å€¼ï¼š8)
# numberOfPinnedPosts = 8

# æ—¥æœŸæ ¼å¼ã€‚è¯·æŸ¥çœ‹ https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference äº†è§£è¯¦ç»†ä¿¡æ¯ã€‚
# dateFormat = "2006-01-02" # é»˜è®¤ä¸º "Jan 2, 2006"ã€‚
# customFonts = false # åˆ‡æ¢ä¸º trueï¼Œå¦‚æœæ‚¨æƒ³ä»…ä½¿ç”¨è‡ªå®šä¹‰å­—ä½“ã€‚

# åˆ›å»ºæ­¤ç½‘ç«™çš„å¹´ä»½ï¼Œæ­¤å€¼ç”¨äºé¡µè„šä¸­çš„ç‰ˆæƒå£°æ˜ã€‚
# since = 2016

# æ ¹æ®â€œç³»åˆ—â€åˆ†ç±»åœ¨æ–‡ç« æœ«å°¾æ˜¾ç¤ºç›¸å…³å†…å®¹ã€‚å¯ä»¥åœ¨æ–‡ç« å‰ç½®å…ƒæ•°æ®ä¸­è®¾ç½®ã€‚
# showRelatedInArticle = false
# showRelatedInSidebar = false

[plausible_analytics]
enable = false # è¦å¯ç”¨ plausible åˆ†æï¼Œè¯·è®¾ç½®ä¸º trueã€‚
websiteDomain = "example.com" # æ‚¨çš„ç½‘ç«™åŸŸåï¼Œåœ¨å¤§å¤šæ•°æƒ…å†µä¸‹ä¸æ‚¨çš„åŸºæœ¬ URL ç›¸åŒ
# plausibleDomain = "plausible.io" # é»˜è®¤è®¾ç½®ä¸º plausible.ioï¼Œä»…åœ¨ä½¿ç”¨è‡ªæ‰˜ç®¡çš„ plausible æ—¶éœ€è¦
# scritpName = "plausible" # é»˜è®¤è®¾ç½®ä¸º plausibleï¼Œä»…åœ¨ä½¿ç”¨è‡ªå®šä¹‰è„šæœ¬åç§°æ—¶éœ€è¦

[matomo_analytics]
# å¯ç”¨ matomo åˆ†æã€‚å°†å…¶æ›´æ”¹ä¸ºâ€œtrueâ€ä»¥å¯ç”¨ã€‚
enable = false
# æ‚¨çš„ç½‘ç«™åŸŸåï¼Œåœ¨å¤§å¤šæ•°æƒ…å†µä¸‹ä¸æ‚¨çš„åŸºæœ¬ URL ç›¸åŒï¼Œè¿™æ˜¯å¿…éœ€çš„ã€‚
websiteDomain = "example.com"
# è®¾ç½®ä¸º Matomo åŸŸã€‚
matomoDomain = "matomo.example.com"
# é»˜è®¤è®¾ç½®ä¸º 1ï¼Œå°†å…¶æ›´æ”¹ä¸ºæ­£åœ¨è·Ÿè¸ªçš„ç«™ç‚¹ IDã€‚
matomoSiteID = "1"


# ç½‘ç«™ä½œè€… 
[author]
name = "Admin"
# photo = "images/jane-doe.png" # å¦‚æœæ‚¨æƒ³åœ¨ä¾§è¾¹æ ä¸Šæ˜¾ç¤ºä½œè€…ç…§ç‰‡ï¼Œè¯·åŒ…å«æ­¤å†…å®¹

# [apiBaseUrl]
# apiBaseUrl = 'https://api.innovate.quwancode.com/api_1_0'


[user]
isLogin  = true
userName = 'aaa'
userinfo = []